name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }} # secret 변수(토큰)
        with:
          source-directory: "output"
          destination-github-username: RohSungKyun # 개인 레포 주인 username
          destination-repository-name: PWA_FE # 개인-레포-이름
          user-email: ${{ secrets.EMAIL }} # secret 변수(이메일)
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main # 개인 레포 브랜치(vercel과 연동된 브랜치)

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
